### ISSUE TITLE
Does not work with the root directory (BUILD_DIR = /.)

### ISSUE THREAD

**Issue by Tgjmjgj** [maxheld83/ghpages#5]
It seems that the command `add .` from your script does not work correctly for the root dir in `BUILD_DIR`.

Here is the output I get with `BUILD_DIR = /.`.
If I change the value, for example, to `dist/` everything will work fine.

```
#################################################
Changing directory to 'BUILD_DIR' /. ...
#################################################
Now deploying to GitHub Pages...
warning: adding embedded git repository: github/workspace
hint: You've added another git repository inside your current repository.
hint: Clones of the outer repository will not contain the contents of
hint: the embedded repository and will not know how to obtain it.
hint: If you meant to add a submodule, use:
hint: 
hint: 	git submodule add <url> github/workspace
hint: 
hint: If you added this path by mistake, you can remove it from the
hint: index with:
hint: 
hint: 	git rm --cached github/workspace
hint: 
hint: See "git help submodule" for more information.
error: open("proc/1/mem"): Permission denied
error: unable to index file proc/1/mem
fatal: adding files failed
Initialized empty Git repository in /.git/

### FAILED GitHub Pages Deploy 17:24:08Z (10.705s)
````

**Comment by leny** [comment]
It works when `BUILD_DIR = .`

**Comment by Tgjmjgj** [comment]
Ugh, yes, it is obvious. I did not think. Just in RADME was a typo.
Thanks!

**Comment by maxheld83** [comment]
ah yes, thanks @leny. Will craft a release hopefully later today and then this is good to go.

**Comment by maxheld83** [comment]
just out of curiosity, @Tgjmjgj: what's the use case for deploying from `.`? 
Wouldn't you rather then just serve from that branch directly?

**Comment by Tgjmjgj** [comment]
@maxheld83 Wow, I didn't know it was possible. I think that this is the only way with the gh-pages branch for the project repository...
Now I see that there are many options in the project settings.
It seems your curiosity helped me a lot! Thank you for the advise!
