### ISSUE TITLE
Return neutral code when nothing to commit

### ISSUE THREAD

**Issue by leny** [maxheld83/ghpages#7]
Hi, I use this great action to deploy my website after building the assets with npm scripts.

The fact is that this action also trigger the workflow (as it creates a commit/push on `master`), so it re-run the workflow... and crash with this (logical) message, as there's noting new to commit.

```
#################################################
Changing directory to 'BUILD_DIR' . ...
#################################################
Now deploying to GitHub Pages...
Reinitialized existing Git repository in /github/workspace/.git/
On branch master
nothing to commit, working tree clean

### FAILED deploy: gh-pages 10:37:26Z (601ms)
```

Maybe, in that specific case, it should be great to return a [`78` exit code](https://developer.github.com/actions/creating-github-actions/accessing-the-runtime-environment/#exit-codes-and-statuses), indicating a `neutral` stop.

**Comment by maxheld83** [comment]
closing this in favor of further discussion in #9
